# SWE-agent setting for curation tasks
SWE-agent:
  dir: ../SWE-agent   # Path to the SWE-agent codebase
  run_name: swe-agent_default     # Default run name for the SWE-agent
  model:
    name: claude-sonnet-4-5-20250929
    per_instance_cost_limit: 5.0
    per_instance_call_limit: 100
  agent_env: sweagent1.1.0   # Conda environment name for the SWE-agent
  config_name: susvibes_curate   # Name of configuration file for the SWE-agent
  num_workers: 10
# Env-agent setting for creating isolated execution environment images
Env-agent:
  dir: ../Env-agent   # Path to the Env-agent codebase
  run_name: env-agent_default     # Default run name for the Env-agent
  model: 
    name: claude-sonnet-4-5-20250929
    per_instance_cost_limit: 10.0
    per_instance_call_limit: 200
  agent_env: envagent1.1.0   # Conda environment name for the Env-agent
  config_name: susvibes_env_setup   # Name of configuration file for the Env-agent
  num_workers: 5
